baseURL = "http://mangatmodi.github.io"
title = "Mangat Rai Modi"
paginate = 5
theme = "hugo-PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpored = false
googleAnalytics = "UA-123-45"
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Mangat Rai Modi"
description = "Contains About me, and my blog posts"
author = "Me"
images = "<link or path of image for opengraph, twitter-cards>"
ShowReadingTime = true
ShowShareButtons = true
comments = true
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = false

  [params.assets]
  favicon = "<path / external url>"

  [params.label]
  text = "Home"

  [params.profileMode]
  enabled = true
  title = "Mangat Rai Modi"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "This is Mangat Rai Modi. You will find here some blog posts."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/mangatmodi"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/1699956/mangat-rai-modi"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mangatmodi"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mangat-rai-12a1b122/"


  [[params.socialIcons]]
  name = "email"
  url = "mailto:mangatmodi@gmail.com"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

