baseURL = "https://www.mangatmodi.com"
title = "Mangat Rai Modi"
paginate = 5
theme = "hugo-PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpored = false
googleAnalytics = "UA-123-45"
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Mangat Rai Modi"
description = "Space for my blog on technology/or not-technology things"
author = "Mangat rai Modi"
images = "<link or path of image for opengraph, twitter-cards>"
ShowReadingTime = true
ShowShareButtons = true
comments = true
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = false

  [params.assets]
  favicon = "<path / external url>"

  [params.label]
  text = "Home"

  [params.profileMode]
  enabled = false
  title = "Mangat Rai Modi"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "This is Mangat Rai Modi. You will find my notes (mostly rants) on various technology topics. My interests are around Highly scalable architecture, Concurrency and Distributed systems. I am also fond of classical rock music and various forms of fitness training."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/mangatmodi"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/1699956/mangat-rai-modi"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mangatmodi"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mangat-rai-12a1b122/"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:mangatmodi@gmail.com"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 10

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
